yuukiHosi
ISC-MakeIT/designer-50knocks pull request #1
Opened 2019-05-29 09:29 UTC by yuuki0828

2019-05-29 09:36 UTC, moya0423 commented
<title></title>タグの中身を問題名に変えてくれるとなおいいかと！
他は完璧です！

2019-05-30 02:22 UTC, ghost requested changes

2019-05-30 02:22 UTC, 10fuga-a commented on YuukiHosi/2/createSection.html
> + <br>我輩は猫である。名前はまだ無い。</br>
タグは基本的に`<開始タグ></閉じタグ>`のワンセットですが、一部例外があります。
代表的なところだと、`<meta>` `<img>` `<br>`がそれにあたります。
基礎の部分は来週からあらためて一緒にやっていきたいと思うのですが、知らないタグを使う場合には`使い方`をぐぐってから使っていきましょう👌

2019-05-30 02:37 UTC, ghost requested changes

2019-05-30 02:37 UTC, 10fuga-a commented on YuukiHosi/2/createSection.html
> + <br>我輩は猫である。名前はまだ無い。</br>
<br>は行送りをしたい文末に書くのがスマートですね。
</br>がもういっこのこっております！

2019-05-30 02:37 UTC, 10fuga-a commented on YuukiHosi/3/form.html
> + <form action="cgi"-bin/formmail.cgi"method="get">
ここの部分、バグりそうな記述になっています。

2019-05-30 02:37 UTC, 10fuga-a commented on YuukiHosi/3/form.html
> +    名前：<br><input type="text" name="name"size="40">
フォーム内の初期値を設定したい！
初期値の設定の仕方は調べて見ましょう◎

2019-05-30 02:37 UTC, 10fuga-a commented on YuukiHosi/3/form.html
> +    </select>
性別の選択が消えている気がする🙄

2019-05-30 02:37 UTC, 10fuga-a commented on YuukiHosi/3/form.html
> +    パスワード： <br><input type="password" name="password"size="40">
typeがきちんと適したものに設定されておりgoodです！

2019-05-30 02:43 UTC, 10fuga-a commented on YuukiHosi/3/form.html
> +    名前：<br><input type="text" name="name"size="40">
あと`入力必須`の設定が抜けていますね。
inputタグは要素が多くて覚えるの大変ですが、見ながらでも良いので要件を満たすものを目指して修正してみてください！

2019-07-19 17:34 UTC, closed without merging